name: RSS Feed Workflow

on:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  combine_rss_feeds:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script to combine RSS feeds
        run: python scripts/rss/combine_rss.py
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_GUILD: ${{ secrets.DISCORD_GUILD }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          OPENAI: ${{ secrets.OPENAI }}

      - name: Run script to share new entries to Discord
        run: python scripts/rss/post_to_discord.py
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_GUILD: ${{ secrets.DISCORD_GUILD }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          OPENAI: ${{ secrets.OPENAI }}

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          git add combined_rss_feed.xml
          git add sent_entries.txt
          git commit -m "Update combined RSS feed and shared new Discord entries"
          git push
        env:
          GIT_AUTH_TOKEN: ${{ secrets.ACTIONS_TOKEN }}

