name: RSS Feed Workflow

on:
  schedule:
    - cron: '0 * * * *' # This will run the workflow every hour. Adjust the cron schedule as needed.

jobs:
  combine_rss_feeds:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script to combine RSS feeds
        run: python scripts/rss/combine_rss.py

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          git add combined_rss_feed.xml
          git commit -m "Update combined RSS feed"
          git push
        env:
          GIT_AUTH_TOKEN: ${{ secrets.ACTIONS_TOKEN }}

